### PR TITLE
Add .editorconfig file with preferred config

### PR DESCRIPTION
**Pull request by faahim**
Adds a `.editorconfig` file at the project root with the preferred config.

This should address issue #41 :slightly_smiling_face:

### CODE REVIEW

**Comment by faahim** [comment]
Woo these CI tests are soo coool! :heart_eyes:

**Comment by DanielRuf** [comment]
Hi @faahim,

many thanks for your PR. I will merge it very soon.

**Comment by DanielRuf** [comment]
Hi @faahim,

thanks for your contribution to website-checks.

I have manually cherry-picked your changes. Please create a separate branch in the future.

**Comment by faahim** [comment]
Hi @DanielRuf,
Thanks so much taking a look and merging it! 😄 

Sorry, it caused you some extra work, I'll be sure to create separate branch from now. Thanks for pointing it out.

**Pull request closed without merging**
